### PR TITLE
Change from edema to no-edema

### PR DESCRIPTION
**Pull request by prajurock**
TODO:- update the video link

### CODE REVIEW

**Review by lvonasek — CHANGES_REQUESTED** [review]
1) Please change '<string name="link" translatable="false"' to '<string name="edema_link"'
2) Add translations for "edema_link"
3) Remove 'translatable="false"' from selector_yes, selector_no
4) Remove empty pause() method

**Comment by prajurock** [comment]
@lvonasek found one link but that is in Hindi. added in all string

**Comment by lvonasek** [comment]
@prajurock - hindi video is not acceptable for non-Hindi locations. We should have english alternative for other countries.

**Comment by prajurock** [comment]
Ok! Asking shivangi that she can provide.

**Comment by prajurock** [comment]
@lvonasek  link in English added.

**Comment by lvonasek** [comment]
Great, I will test it tomorrow on device and if everything is okay then I merge it and make a build 3.0.3

**Review by lvonasek — APPROVED** [review]

**Pull request merged**
